apiVersion: v1
kind: ServiceAccount
metadata:
  name: fd-agent
  namespace: agentgateway-system
  labels:
    app.kubernetes.io/managed-by: agentgateway-demo
    agentgateway.dev/feature: fd-agent
    app: fd-agent
